services:
  - name: front
    type: web
    env: docker
    docker:
      dockerfile: ./dockerfiles/front/Dockerfile
      buildContext: .
    envVars:
      - key: WATCHPACK_POLLING
        value: "true"
    plan: free
    ports:
      - 3000
    startCommand: "npm run dev"
    mounts:
      - type: volume
        source: ./front
        target: /app

  - name: analyze
    type: web
    env: docker
    docker:
      dockerfile: ./dockerfiles/analyze/Dockerfile
      buildContext: .
    envVars:
      - key: PYTHONPATH
        value: /app
    plan: free
    ports:
      - 8001
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    mounts:
      - type: volume
        source: ./analyze/src
        target: /app